import { useSearchParams, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { getPreviewDocuments, getSingleProspect } from "@/store/data";
import { useToast } from "@/hooks/use-toast";
import { sendContract, changeProspectStatus } from "@/api/api";
import { ContractPreviewAndSend } from "@/components/portal/shared/ContractPreviewAndSend";
import { Property, Prospect } from "@/types/types";

interface ProspectData {
  prospect: Prospect;
  properties: Property[];
}

export default function ProspectContractPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const prospectIdParam = searchParams.get("id");
  const { toast } = useToast();
  const [prospectData, setProspectData] = useState<ProspectData | null>(null);
  const [contractPdfBase64, setContractPdfBase64] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSending, setIsSending] = useState(false);

  useEffect(() => {
    const fetchProspect = async () => {
      if (!prospectIdParam) return;
      try {
        const data = await getSingleProspect({ prospectId: prospectIdParam });
        setProspectData(data ?? null);
      } catch (e) {
        console.error("Error fetching prospect:", e);
        setProspectData(null);
      }
    };
    fetchProspect();
  }, [prospectIdParam]);

  useEffect(() => {
    if (!prospectIdParam) return;
    const id = Number(prospectIdParam);
    if (Number.isNaN(id)) return;
    setLoading(true);
    setError(null);
    getPreviewDocuments({ prospectId: id })
      .then((res: { contractPdf?: string; aoaPdf?: string }) => {
        setContractPdfBase64(res?.contractPdf ?? null);
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : "Failed to load preview");
        setContractPdfBase64(null);
      })
      .finally(() => setLoading(false));
  }, [prospectIdParam]);

  const handleDownload = () => {
    if (!contractPdfBase64) return;
    try {
      const blob = new Blob(
        [Uint8Array.from(atob(contractPdfBase64), (c) => c.charCodeAt(0))],
        { type: "application/pdf" }
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `contract-prospect-${prospectData?.prospect?.id ?? prospectIdParam ?? "contract"}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({
        title: "Download started",
        description: "Contract PDF has been downloaded.",
      });
    } catch {
      toast({
        title: "Download failed",
        description: "Could not save the PDF.",
        variant: "destructive",
      });
    }
  };

  const handleSend = async () => {
    if (!prospectIdParam || !prospectData?.prospect?.id) {
      toast({
        title: "Error",
        description: "Prospect data not loaded.",
        variant: "destructive",
      });
      return;
    }
    const id = prospectData.prospect.id;
    setIsSending(true);
    try {
      await sendContract({ prospectId: id });
      if (prospectData.prospect.status === "CONTACTED") {
        await changeProspectStatus({ prospectId: id, newStatus: "IN_PROGRESS" });
      }
      toast({
        title: "✓ Contract sent for signing",
        description: "Contract has been sent. They will receive an email from DocuSign.",
      });
      navigate(`/portal/prospect?id=${prospectIdParam}`);
    } catch (err) {
      toast({
        title: "Failed to send contract",
        description: err instanceof Error ? err.message : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <ContractPreviewAndSend
      pdfBase64={contractPdfBase64}
      loading={loading}
      error={error}
      onDownload={handleDownload}
      onSend={handleSend}
      isSending={isSending}
      sendDisabled={!prospectData?.prospect?.id}
      title="Contract (generated by server)"
      hasEntity={!!prospectIdParam}
      emptyMessage={
        <p>
          Open this page from a prospect (e.g. Prospect details → Create Contract) to load the contract.
        </p>
      }
    />
  );
}
